version: "3"
services: 
  deepracer-cam:
    image: lshw54/deepracer-cam
    privileged: true
    environment:
      DISPLAY: $DISPLAY
      password: 
      hostIp: 
      QT_X11_NO_MITSHM: 1
    volumes: 
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
  g29-control-mode:
    image: lshw54/g29-control
    privileged: true
    environment: 
      DISPLAY: $DISPLAY
      password: 
      hostIp: 
    volumes: 
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    devices:
      - "/dev/snd"