version: "3"
services: 
  deepracer-cam:
    image: lshw54/deepracer-cam
    privileged: true
    environment:
      DISPLAY: $DISPLAY
      password: $password
      hostIp: $hostIp
      QT_X11_NO_MITSHM: 1
    volumes: 
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
  ps4-controller-mode:
    image: lshw54/ps4-controller
    privileged: true
    environment: 
      DISPLAY: $DISPLAY
      password: $password
      hostIp: $hostIp
    volumes: 
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    devices:
      - "/dev/snd"